title: "PEM :: Product Engineering Management"
description: The intersection of product engineering and engineering management.
google_analytics: 
show_downloads: true
theme: jekyll-theme-slate

gems:
  - jekyll-mentions
