title: Product Engineering Management
description: The intersection of product engineering & engineering management.
markdown: kramdown
google_analytics: false
show_downloads: false
theme: jekyll-theme-slate

gems:
  - jekyll-mentions
