title: DiscoDev
heading: <u>Disco</u>very + <u>Dev</u>elopment
description: Blending the boundary between product & engineering.
email: mike@discodev.xyz
author: Michael Nadel
baseurl: ""
url: "https://discodev.xyz"

github_username: mnadel
linkedin_username: nadel

google_analytics: G-NDT0SRZ197
permalink: /:slug.html

favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)
logo: "logo.png" # name+extension of favicon (which must be put on the root folder)

remote_theme: riggraz/no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: "~/discodev" # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page
  lowercase_titles: false # show titles in lowercase in lists
  show_title: false # show title in homepage

sass:
  style: compressed

markdown: kramdown
paginate: 10
paginate_path: "/posts/page:num/"

plugins:
  - jektex
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-gist
  - jekyll-avatar

jektex:
  cache_dir: ".jektex-cache"
  ignore: ["*.xml"]
  silent: false
  macros:
    - ["\\Q", "\\mathbb{Q}"]
    - ["\\C", "\\mathbb{C}"]
