title: DiscoDev
heading: <u>Disco</u>very + <u>Dev</u>elopment
description: Blending the boundary between product & engineering.
email: mike@discodev.xyz
author: Michael Nadel
baseurl: ""
url: "https://discodev.xyz"

github_username: mnadel
linkedin_username: nadel

google_analytics: UA-172988644-1

markdown: kramdown
paginate: 10
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-gist
  - jekyll-avatar
